# @package __global__

defaults:
  - /solver/musicgen/default
  - _self_
  - /solver/audiogen/evaluation: none
  - override /dset: audio/default

# See config/solver/musicgen/default.yaml for a list of possible values.
# We only keep the most important here.

autocast: true
autocast_dtype: float16

solver: v2agen
sample_rate: ???
channels: ???
compression_model_checkpoint: ???

tokens:
  padding_with_special_token: false

dataset:
  batch_size: 128
  segment_duration: 5
  min_segment_ratio: 1.0  # lower values such as 0.5 result in generations with a lot of silence.
  vfps: ${conditioners.video.jepa.sample_rate}

generate:
  lm:
    prompted_samples: false
    unprompted_samples: true
#     long_samples:
#       generate: true
#       duration: 4.48
#       stride: null
#       datasource:
#         max_sample_rate: 24000
#         max_channels: 2

#         train: null
#         valid: null
#         evaluate: null
#         generate_long: egs/gh/h264_video_25fps_256side_24000hz_aac/test_subset

optim:
  epochs: 100
  updates_per_epoch: 2000
  lr: 1e-4
  optimizer: adamw
  max_norm: 1.0
  adam:
    betas: [0.9, 0.95]
    weight_decay: 0.1
    eps: 1e-8

schedule:
  lr_scheduler: null
