# @package __global__

# This is a minimal debugging configuration
# for V2AGen training solver
defaults:
  - v2agen/default
  - /model: lm/v2agen_lm
  - override /model/lm/model_scale: xsmall
  - override /dset: audio/example
  - _self_

autocast: true
autocast_dtype: float16

compression_model_checkpoint: facebook/encodec_24kHz

channels: 1
sample_rate: 24000

conditioners:
  video:
    jepa:
      use_masking: false
      sample_rate: 25
      autocast_dtype: ${autocast_dtype}

deadlock:
  use: true  # deadlock detection

dataset:
  batch_size: 4
  segment_duration: 5
  sample_on_weight: false  # Uniform sampling all the way
  sample_on_duration: false  # Uniform sampling all the way

generate:
  audio:
    strategy: peak
  lm:
    use_sampling: false
    top_k: 0
    top_p: 0.0

checkpoint:
  save_every: 0
  keep_last: 0

optim:
  epochs: 2
  updates_per_epoch: 10
  optimizer: adamw
  lr: 1e-4

logging:
  log_tensorboard: true

schedule:
  lr_scheduler: null
