# @package __global__

datasource:
  max_sample_rate: 24000
  max_channels: 2

  train: egs/example_video_vgg
  valid: egs/example_video_vgg
  evaluate: egs/example_video_vgg
  generate: egs/example_video_vgg
