# @package __global__

datasource:
  max_sample_rate: 24000
  max_channels: 2

  train: egs/vgg/h264_video_25fps_256side_24000hz_aac/train
  valid: egs/vgg/h264_video_25fps_256side_24000hz_aac/valid
  evaluate: egs/vgg/h264_video_25fps_256side_24000hz_aac/sparse
  generate: egs/vgg/h264_video_25fps_256side_24000hz_aac/sparse
